# Generated by Django 5.2.1 on 2025-06-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0003_user_facebook_id_user_google_id_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_flag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
