# Generated by Django 4.2.5 on 2025-06-20 11:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0007_loginsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginsession',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
