# Generated by Django 4.2.5 on 2025-06-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0008_loginsession_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpattempt',
            name='attempts',
            field=models.IntegerField(default=1),
        ),
    ]
