# Generated by Django 4.2.5 on 2025-06-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_signup', '0010_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpattempt',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
